In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [ ]:
df=pd.read_csv('/content/HR_Analytics.csv')
df.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0

In [ ]:
df.shape

(1480, 38)

In [ ]:
df.isna().sum()

EmpID                        0
Age                          0
AgeGroup                     0
Attrition                    0
BusinessTravel               0
DailyRate                    0
Department                   0
DistanceFromHome             0
Education                    0
EducationField               0
EmployeeCount                0
EmployeeNumber               0
EnvironmentSatisfaction      0
Gender                       0
HourlyRate                   0
JobInvolvement               0
JobLevel                     0
JobRole                      0
JobSatisfaction              0
MaritalStatus                0
MonthlyIncome                0
SalarySlab                   0
MonthlyRate                  0
NumCompaniesWorked           0
Over18                       0
OverTime                     0
PercentSalaryHike            0
PerformanceRating            0
RelationshipSatisfaction     0
StandardHours                0
StockOptionLevel             0
TotalWorkingYears            0
TrainingTimesLastYear        0
WorkLifeBalance              0
YearsAtCompany               0
YearsInCurrentRole           0
YearsSinceLastPromotion      0
YearsWithCurrManager        57
dtype: int64

In [ ]:
df["Attrition"].value_counts()

Attrition
No     1242
Yes     238
Name: count, dtype: int64

In [ ]:
def value_counts_all_columns(df):
    for col in df.columns:
        print(f"\n🔹 Column: {col}")
        print(df[col].value_counts())

In [ ]:
value_counts_all_columns(df)

🔹 Column: EmpID
EmpID
RM1467    2
RM1465    2
RM1468    2
RM1463    2
RM1466    2
         ..
RM693     1
RM683     1
RM657     1
RM642     1
RM1027    1
Name: count, Length: 1470, dtype: int64

🔹 Column: Age
Age
35    78
34    78
31    70
36    70
29    69
32    61
30    60
33    58
38    58
40    57
37    50
27    49
28    48
42    46
39    44
45    41
26    40
41    40
44    33
46    33
43    32
50    31
25    26
24    26
49    25
47    24
55    22
53    19
48    19
51    19
52    18
54    18
22    16
23    14
56    14
58    14
21    13
20    11
59    10
19     9
18     8
60     5
57     4
Name: count, dtype: int64

🔹 Column: AgeGroup
AgeGroup
26-35    611
36-45    471
46-55    228
18-25    123
55+       47
Name: count, dtype: int64

🔹 Column: Attrition
Attrition
No     1242
Yes     238
Name: count, dtype: int64

🔹 Column: BusinessTravel
BusinessTravel
Travel_Rarely        1042
Travel_Frequently     279
Non-Travel            151
TravelRarely            8
Name: count, dtype: int64

🔹 Column: DailyRate
DailyRate
691     6
1082    5
408     5
1329    5
530     5
       ..
536     1
516     1
392     1
211     1
1076    1
Name: count, Length: 886, dtype: int64

🔹 Column: Department
Department
Research & Development    967
Sales                     450
Human Resources            63
Name: count, dtype: int64

🔹 Column: DistanceFromHome
DistanceFromHome
2     212
1     208
10     86
9      85
3      84
7      84
8      81
5      67
4      65
6      60
16     32
24     29
11     29
23     28
29     27
18     26
15     26
28     25
20     25
26     25
25     25
19     22
14     21
12     20
17     20
13     19
22     19
21     18
27     12
Name: count, dtype: int64

🔹 Column: Education
Education
3    578
4    399
2    283
1    172
5     48
Name: count, dtype: int64

🔹 Column: EducationField
EducationField
Life Sciences       607
Medical             470
Marketing           161
Technical Degree    132
Other                83
Human Resources      27
Name: count, dtype: int64

🔹 Column: EmployeeCount
EmployeeCount
1    1480
Name: count, dtype: int64

🔹 Column: EmployeeNumber
EmployeeNumber
2062    2
2060    2
2064    2
2056    2
2061    2
       ..
966     1
951     1
911     1
889     1
1446    1
Name: count, Length: 1470, dtype: int64

🔹 Column: EnvironmentSatisfaction
EnvironmentSatisfaction
3    454
4    451
2    291
1    284
Name: count, dtype: int64

🔹 Column: Gender
Gender
Male      889
Female    591
Name: count, dtype: int64

🔹 Column: HourlyRate
HourlyRate
66    29
42    29
98    28
84    28
48    28
      ..
31    15
68    14
53    14
38    13
34    12
Name: count, Length: 71, dtype: int64

🔹 Column: JobInvolvement
JobInvolvement
3    869
2    381
4    147
1     83
Name: count, dtype: int64

🔹 Column: JobLevel
JobLevel
1    545
2    539
3    220
4    107
5     69
Name: count, dtype: int64

🔹 Column: JobRole
JobRole
Sales Executive              329
Research Scientist           293
Laboratory Technician        261
Manufacturing Director       147
Healthcare Representative    132
Manager                      102
Sales Representative          84
Research Director             80
Human Resources               52
Name: count, dtype: int64

🔹 Column: JobSatisfaction
JobSatisfaction
4    461
3    444
1    293
2    282
Name: count, dtype: int64

🔹 Column: MaritalStatus
MaritalStatus
Married     679
Single      473
Divorced    328
Name: count, dtype: int64

🔹 Column: MonthlyIncome
MonthlyIncome
6142     4
2342     4
5562     3
2559     3
2610     3
        ..
1051     1
5220     1
10266    1
19566    1
10512    1
Name: count, Length: 1349, dtype: int64

🔹 Column: SalarySlab
SalarySlab
Upto 5k    753
5k-10k     444
10k-15k    150
15k+       133
Name: count, dtype: int64

🔹 Column: MonthlyRate
MonthlyRate
9150     3
4223     3
24444    2
17001    2
10228    2
        ..
11693    1
2338     1
7331     1
14947    1
18783    1
Name: count, Length: 1427, dtype: int64

🔹 Column: NumCompaniesWorked
NumCompaniesWorked
1    523
0    200
3    159
2    148
4    142
7     74
6     70
5     63
9     52
8     49
Name: count, dtype: int64

🔹 Column: Over18
Over18
Y    1480
Name: count, dtype: int64

🔹 Column: OverTime
OverTime
No     1062
Yes     418
Name: count, dtype: int64

🔹 Column: PercentSalaryHike
PercentSalaryHike
11    211
13    210
14    203
12    199
15    102
18     90
17     83
16     78
19     77
20     56
22     56
21     48
23     28
24     21
25     18
Name: count, dtype: int64

🔹 Column: PerformanceRating
PerformanceRating
3    1253
4     227
Name: count, dtype: int64

🔹 Column: RelationshipSatisfaction
RelationshipSatisfaction
3    460
4    434
2    307
1    279
Name: count, dtype: int64

🔹 Column: StandardHours
StandardHours
80    1480
Name: count, dtype: int64

🔹 Column: StockOptionLevel
StockOptionLevel
0    636
1    601
2    158
3     85
Name: count, dtype: int64

🔹 Column: TotalWorkingYears
TotalWorkingYears
10    203
6     127
8     103
9      97
5      90
1      81
7      81
4      63
12     48
3      42
15     40
16     37
13     36
11     36
21     35
17     35
14     31
2      31
20     31
18     27
23     22
19     22
22     21
24     18
26     14
25     14
28     14
0      11
29     10
31      9
32      9
27      7
30      7
33      7
36      6
34      5
37      4
35      3
40      2
38      1
Name: count, dtype: int64

🔹 Column: TrainingTimesLastYear
TrainingTimesLastYear
2    550
3    496
4    123
5    120
1     71
6     65
0     55
Name: count, dtype: int64

🔹 Column: WorkLifeBalance
WorkLifeBalance
3    899
2    346
4    154
1     81
Name: count, dtype: int64

🔹 Column: YearsAtCompany
YearsAtCompany
5     198
1     171
3     129
2     127
10    120
4     112
7      91
9      84
8      80
6      77
0      44
11     32
20     28
13     24
15     20
14     18
22     15
21     14
12     14
18     13
16     12
19     11
17      9
24      6
33      5
26      4
25      4
32      3
31      3
27      2
23      2
29      2
36      2
30      1
34      1
37      1
40      1
Name: count, dtype: int64

🔹 Column: YearsInCurrentRole
YearsInCurrentRole
2     376
0     244
7     223
3     136
4     106
8      89
9      68
1      57
6      38
5      36
10     29
11     22
13     14
14     11
12     10
15      8
16      7
17      4
18      2
Name: count, dtype: int64

🔹 Column: YearsSinceLastPromotion
YearsSinceLastPromotion
0     586
1     360
2     160
7      76
4      61
3      52
5      45
6      32
11     24
8      18
9      18
15     13
13     10
12     10
14      9
10      6
Name: count, dtype: int64

🔹 Column: YearsWithCurrManager
YearsWithCurrManager
2.0     330
0.0     253
7.0     211
3.0     139
8.0     100
4.0      95
1.0      76
9.0      61
5.0      31
6.0      30
10.0     27
11.0     21
12.0     17
13.0     14
17.0      6
15.0      5
14.0      5
16.0      2
Name: count, dtype: int64

In [ ]:
df["YearsWithCurrManager"]=df["YearsWithCurrManager"].fillna(df["YearsWithCurrManager"].median())

In [ ]:
df["YearsWithCurrManager"].isna().sum()

np.int64(0)

In [ ]:
df=df.drop(columns=["EmpID" ,"EmployeeCount" , "EmployeeNumber"] ,axis=1 )

In [ ]:
df.shape

(1480, 35)

In [ ]:
df.isna().sum()

Age                         0
AgeGroup                    0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
SalarySlab                  0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [ ]:
(df == "").sum()

Age                         0
AgeGroup                    0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
SalarySlab                  0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [ ]:
num_cols = df.select_dtypes(include=['int64', 'float64'])
num_cols.columns

Index(['Age', 'DailyRate', 'DistanceFromHome', 'Education',
       'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel',
       'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StandardHours', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [ ]:
cat_cols=df.select_dtypes(include=['object' , 'category'])
cat_cols.head()

,AgeGroup,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,SalarySlab,Over18,OverTime
0,18-25,Yes,Travel_Rarely,Research & Development,Life Sciences,Male,Laboratory Technician,Single,Upto 5k,Y,No
1,18-25,No,Travel_Rarely,Sales,Medical,Female,Sales Representative,Single,Upto 5k,Y,No
2,18-25,Yes,Travel_Frequently,Sales,Marketing,Male,Sales Representative,Single,Upto 5k,Y,Yes
3,18-25,No,Non-Travel,Research & Development,Life Sciences,Male,Research Scientist,Single,Upto 5k,Y,No
4,18-25,Yes,Non-Travel,Research & Development,Medical,Male,Laboratory Technician,Single,Upto 5k,Y,No

In [ ]:
print(num_cols.shape)
print(cat_cols.shape)

(1480, 24)
(1480, 11)

In [ ]:
num_cols.head()

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,18,230,3,3,3,54,3,1,3,1420,...,3,80,0,0,2,3,0,0,0,0.0
1,18,812,10,3,4,69,2,1,3,1200,...,1,80,0,0,2,3,0,0,0,0.0
2,18,1306,5,3,2,69,3,1,2,1878,...,4,80,0,0,3,3,0,0,0,0.0
3,18,287,5,2,2,73,3,1,4,1051,...,4,80,0,0,2,3,0,0,0,0.0
4,18,247,8,1,3,80,3,1,3,1904,...,4,80,0,0,0,3,0,0,0,0.0

In [ ]:
df["Attrition"].value_counts()

Attrition
No     1242
Yes     238
Name: count, dtype: int64

In [ ]:
X=df.drop(columns="Attrition" , axis=1)
Y=df["Attrition"]

In [ ]:
print(X.shape)
print(Y.shape)

(1480, 34)
(1480,)

In [ ]:
X_train, X_test , Y_train , Y_test=train_test_split(X , Y , test_size=0.2 , stratify=Y , random_state=3)

In [ ]:
print(X.shape , X_train.shape , X_test.shape)
print(Y.shape , Y_train.shape , Y_test.shape )

(1480, 34) (1184, 34) (296, 34)
(1480,) (1184,) (296,)

In [ ]:
from pandas.core.arrays import sparse
encoder=OneHotEncoder(drop="first" , handle_unknown="ignore" , sparse_output=False)

In [ ]:
cat_cols = X.select_dtypes(include=["object"]).columns
num_cols = X.select_dtypes(exclude=["object"]).columns

In [ ]:
X_train_cat=encoder.fit_transform(X_train[cat_cols])

In [ ]:
X_test_cat=encoder.fit_transform(X_test[cat_cols])

In [ ]:
encoded_cols=encoder.get_feature_names_out(cat_cols)
X_train_cat=pd.DataFrame(X_train_cat, columns=encoded_cols)
X_test_cat=pd.DataFrame(X_test_cat , columns=encoded_cols)

In [ ]:
X_train_cat.index=X_train.index
X_test_cat.index=X_test.index

In [ ]:
scaler=StandardScaler()

In [ ]:
X_train_stand=scaler.fit_transform(X_train[num_cols])

In [ ]:
X_test_stand=scaler.transform(X_test[num_cols])

In [ ]:
scaled_cols=scaler.get_feature_names_out(num_cols)
X_train_stand=pd.DataFrame(X_train_stand , columns=scaled_cols)
X_test_stand=pd.DataFrame(X_test_stand , columns=scaled_cols)

In [ ]:
X_train_stand.head()

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
381,-0.738642,0.010336,0.832008,-1.850929,-0.652061,-1.604893,0.37236,-0.939416,1.142338,-0.756464,...,-0.644635,0.0,0.247494,-0.141165,-0.607842,-1.054115,0.505188,-1.176091,-0.674286,1.130097
1320,1.463704,-0.243785,-0.891913,0.098804,0.259438,-0.078238,0.37236,1.782286,0.234601,2.420587,...,1.194516,0.0,-0.934089,2.442137,0.171882,0.357731,-0.482117,-0.328389,-0.674286,-0.305563
1352,1.573822,-0.046966,-0.522501,0.098804,0.259438,0.906701,0.37236,1.782286,-0.673136,1.643793,...,-0.644635,0.0,0.247494,2.829632,-0.607842,0.357731,4.289857,1.367015,-0.674286,1.704362
946,0.252414,0.114974,1.201420,1.073670,1.170937,-1.210918,0.37236,-0.032182,1.142338,-0.532864,...,-0.644635,0.0,2.610659,-0.528661,-0.607842,0.357731,-0.811219,-0.610956,-0.059931,-0.592695
540,-0.408290,-0.652371,-1.015050,1.073670,1.170937,-0.127485,0.37236,-0.939416,1.142338,-0.794304,...,0.274941,0.0,-0.934089,-0.141165,-0.607842,-1.054115,0.505188,1.367015,1.475958,1.130097

In [ ]:
X_train_stand.index=X_train.index
X_test_stand.index=X_test.index

In [ ]:
X_train_final=pd.concat([X_train_stand , X_train_cat] , axis=1)
X_test_final=pd.concat([X_test_stand , X_test_cat] , axis=1)

In [ ]:
X_train_final.head()

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,SalarySlab_15k+,SalarySlab_5k-10k,SalarySlab_Upto 5k,OverTime_Yes
381,-0.738642,0.010336,0.832008,-1.850929,-0.652061,-1.604893,0.37236,-0.939416,1.142338,-0.756464,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1320,1.463704,-0.243785,-0.891913,0.098804,0.259438,-0.078238,0.37236,1.782286,0.234601,2.420587,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
1352,1.573822,-0.046966,-0.522501,0.098804,0.259438,0.906701,0.37236,1.782286,-0.673136,1.643793,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
946,0.252414,0.114974,1.201420,1.073670,1.170937,-1.210918,0.37236,-0.032182,1.142338,-0.532864,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
540,-0.408290,-0.652371,-1.015050,1.073670,1.170937,-0.127485,0.37236,-0.939416,1.142338,-0.794304,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0

In [ ]:
print(X.shape , X_train_final.shape , X_test_final.shape)

(1480, 34) (1184, 53) (296, 53)

In [ ]:
print(Y.shape , Y_train.shape , Y_test.shape)

(1480,) (1184,) (296,)

In [ ]:
models=[LogisticRegression(max_iter=10000) , SVC() , RandomForestClassifier(random_state=1)]

In [ ]:
hyper_param={'log_reg':{
  'C':[1 , 5 , 10 , 20]
},

'svc_param':{
    'kernel':['linear' , 'rbf' , 'poly' , 'sigmoid'],
    'C':[1,5 , 10 , 20]
},

'random_param':{
    'n_estimators':[10 , 30 , 70 , 100]
}             }

In [ ]:
model_list=list(hyper_param.keys())

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_train_enc = le.fit_transform(Y_train)
y_test_enc  = le.transform(Y_test)

In [ ]:
hyper_param[model_list[0]]

{'C': [1, 5, 10, 20]}

In [ ]:
def model_evaluations(model_using , params):

  result=[]

  i=0

  for model in model_using:

    key=model_list[i]

    param=params[key]

    i+=1

    classifier=GridSearchCV(model , param , cv=5)

    classifier.fit(X_train_final , y_train_enc)

    result.append({'model_used':model ,
                   'best_param':classifier.best_params_
                   ,
                   'best_score':classifier.best_score_}
                  )
  result=pd.DataFrame(result , columns=['model_used' , 'best_param' , 'best_score'])

  return result

In [ ]:
model_evaluations(models, hyper_param)

,model_used,best_param,best_score
0,LogisticRegression(max_iter=10000),{'C': 1},0.878384
1,SVC(),"{'C': 10, 'kernel': 'linear'}",0.881756
2,RandomForestClassifier(random_state=1),{'n_estimators': 30},0.851341

In [ ]:
best_model_work=SVC(kernel='linear', C=10 , class_weight="balanced")

In [ ]:
best_model_work.fit(X_train_final , y_train_enc)

SVC(C=10, class_weight='balanced', kernel='linear')

In [ ]:
X_train_pred=best_model_work.predict(X_train_final)
accuracy=accuracy_score(y_train_enc, X_train_pred)
precision=precision_score(y_train_enc, X_train_pred)
recall=recall_score(y_train_enc, X_train_pred)
f1=f1_score(y_train_enc, X_train_pred)
print("training accuracy =" , round((accuracy*100), 2) ,'%')
print("training precision =" , round((precision*100), 2) ,'%')
print("training recall =" , round((recall*100), 2) ,'%')
print("training f1 =" , round((f1*100), 2) ,'%')
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_train_enc, X_train_pred)
print(cm)

training accuracy = 80.41 %
training precision = 44.2 %
training recall = 84.21 %
training f1 = 57.97 %
[[792 202]
 [ 30 160]]

In [ ]:
X_test_pred=best_model_work.predict(X_test_final)
accuracy=accuracy_score(y_test_enc, X_test_pred)
precision=precision_score(y_test_enc, X_test_pred)
recall=recall_score(y_test_enc, X_test_pred)
f1=f1_score(y_test_enc, X_test_pred)
print("test accuracy =" , round((accuracy*100), 2) ,'%')
print("test precision =" , round((precision*100), 2) ,'%')
print("test recall =" , round((recall*100), 2) ,'%')
print("test f1 =" , round((f1*100), 2) ,'%')
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test_enc, X_test_pred)
print(cm)

test accuracy = 81.76 %
test precision = 45.95 %
test recall = 70.83 %
test f1 = 55.74 %
[[208  40]
 [ 14  34]]

In [ ]:
best_model_work2=RandomForestClassifier(
    class_weight="balanced",
    max_depth=5,
    min_samples_leaf=10,
    random_state=42
)

In [ ]:
best_model_work2.fit(X_train_final , y_train_enc)

RandomForestClassifier(class_weight='balanced', max_depth=5,
                       min_samples_leaf=10, random_state=42)

In [ ]:
X_train_pred=best_model_work2.predict(X_train_final)
accuracy=accuracy_score(y_train_enc, X_train_pred)
precision=precision_score(y_train_enc, X_train_pred)
recall=recall_score(y_train_enc, X_train_pred)
f1=f1_score(y_train_enc, X_train_pred)
print("training accuracy =" , round((accuracy*100), 2) ,'%')
print("training precision =" , round((precision*100), 2) ,'%')
print("training recall =" , round((recall*100), 2) ,'%')
print("training f1 =" , round((f1*100), 2) ,'%')
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_train_enc, X_train_pred)
print(cm)

training accuracy = 87.33 %
training precision = 58.4 %
training recall = 73.16 %
training f1 = 64.95 %
[[895  99]
 [ 51 139]]

In [ ]:
X_test_pred=best_model_work2.predict(X_test_final)
accuracy=accuracy_score(y_test_enc, X_test_pred)
precision=precision_score(y_test_enc, X_test_pred)
recall=recall_score(y_test_enc, X_test_pred)
f1=f1_score(y_test_enc, X_test_pred)
print("test accuracy =" , round((accuracy*100), 2) ,'%')
print("test precision =" , round((precision*100), 2) ,'%')
print("test recall =" , round((recall*100), 2) ,'%')
print("test f1 =" , round((f1*100), 2) ,'%')
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test_enc, X_test_pred)
print(cm)

test accuracy = 85.81 %
test precision = 87.5 %
test recall = 14.58 %
test f1 = 25.0 %
[[247   1]
 [ 41   7]]

In [ ]:
best_model_work3=LogisticRegression(C=1, class_weight="balanced")

In [ ]:
best_model_work3.fit(X_train_final , y_train_enc)

LogisticRegression(C=1, class_weight='balanced')

In [ ]:
X_train_pred=best_model_work3.predict(X_train_final)
accuracy=accuracy_score(y_train_enc, X_train_pred)
precision=precision_score(y_train_enc, X_train_pred)
recall=recall_score(y_train_enc, X_train_pred)
f1=f1_score(y_train_enc, X_train_pred)
print("training accuracy =" , round((accuracy*100), 2) ,'%')
print("training precision =" , round((precision*100), 2) ,'%')
print("training recall =" , round((recall*100), 2) ,'%')
print("training f1 =" , round((f1*100), 2) ,'%')
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_train_enc, X_train_pred)
print(cm)

training accuracy = 79.05 %
training precision = 41.99 %
training recall = 80.0 %
training f1 = 55.07 %
[[784 210]
 [ 38 152]]

In [ ]:
X_test_pred=best_model_work3.predict(X_test_final)
accuracy=accuracy_score(y_test_enc, X_test_pred)
precision=precision_score(y_test_enc, X_test_pred)
recall=recall_score(y_test_enc, X_test_pred)
f1=f1_score(y_test_enc, X_test_pred)
print("test accuracy =" , round((accuracy*100), 2) ,'%')
print("test precision =" , round((precision*100), 2) ,'%')
print("test recall =" , round((recall*100), 2) ,'%')
print("test f1 =" , round((f1*100), 2) ,'%')
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test_enc, X_test_pred)
print(cm)

test accuracy = 81.08 %
test precision = 44.59 %
test recall = 68.75 %
test f1 = 54.1 %
[[207  41]
 [ 15  33]]